// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package validate

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"at least one of [%s] should be valued": 9,
	"cound be malformed":                    2,
	"has a maximum length [%d]":             5,
	"has a minimum length [%d]":             4,
	"is not a %s":                           1,
	"not allow empty":                       0,
	"should be greater than equal [%d], current value is [%d]": 7,
	"should be less than equal [%d], current value is [%d]":    8,
	"should be one of [%s], current value is [%d]":             6,
	"should be one of [%s], current value is [%s]":             3,
}

var enIndex = []uint32{ // 11 elements
	0x00000000, 0x00000010, 0x0000001f, 0x00000032,
	0x00000065, 0x00000082, 0x0000009f, 0x000000d2,
	0x00000111, 0x0000014d, 0x00000176,
} // Size: 68 bytes

const enData string = "" + // Size: 374 bytes
	"\x02not allow empty\x02is not a %[1]s\x02cound be malformed\x02should be" +
	" one of [%[1]s], current value is [%[2]s]\x02has a minimum length [%[1]d" +
	"]\x02has a maximum length [%[1]d]\x02should be one of [%[1]s], current v" +
	"alue is [%[2]d]\x02should be greater than equal [%[1]d], current value i" +
	"s [%[2]d]\x02should be less than equal [%[1]d], current value is [%[2]d]" +
	"\x02at least one of [%[1]s] should be valued"

var zhIndex = []uint32{ // 11 elements
	0x00000000, 0x00000010, 0x0000001c, 0x00000029,
	0x0000005d, 0x00000083, 0x000000a9, 0x000000dd,
	0x0000010d, 0x0000013d, 0x00000160,
} // Size: 68 bytes

const zhData string = "" + // Size: 352 bytes
	"\x02不允许为空\x02不是%[1]s\x02格式错误\x02应该是[%[1]s]中的一个，当前值为 [%[2]s]\x02不满足最小长度[%" +
	"[1]d]的约束\x02不满足最大长度[%[1]d]的约束\x02应该是[%[1]s]中的一个，当前值为 [%[2]d]\x02应该大于等于[%" +
	"[1]d]，当前值为[%[2]d]\x02应该小于等于[%[1]d]，当前值为[%[2]d]\x02至少[%[1]s]中的一个被赋值"

	// Total table size 862 bytes (0KiB); checksum: 63589230
